# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddBook(object):
    def setupUi(self, AddBook):
        AddBook.setObjectName("AddBook")
        AddBook.resize(287, 289)
        font = QtGui.QFont()
        font.setFamily("Manrope")
        AddBook.setFont(font)
        self.enter_title = QtWidgets.QLineEdit(AddBook)
        self.enter_title.setGeometry(QtCore.QRect(150, 20, 113, 20))
        self.enter_title.setObjectName("enter_title")

        self.enter_writer = QtWidgets.QLineEdit(AddBook)
        self.enter_writer.setGeometry(QtCore.QRect(150, 60, 113, 20))
        self.enter_writer.setObjectName("enter_writer")

        self.enter_publisher = QtWidgets.QLineEdit(AddBook)
        self.enter_publisher.setGeometry(QtCore.QRect(150, 100, 113, 20))
        self.enter_publisher.setObjectName("enter_publisher")

        self.enter_lang = QtWidgets.QLineEdit(AddBook)
        self.enter_lang.setGeometry(QtCore.QRect(150, 140, 113, 20))
        self.enter_lang.setObjectName("enter_lang")

        # ПЕРЕНЕСТИ КОД В main.py И СДЕЛАТЬ ДОБАВЛЕНИЕ ЖАНРОВ В ТАБЛИЦУ (НАДО ЕЕ ПРЕДВАРИТЕЛЬНО ПОЧИСТИТЬ)
        # ТАКЖЕ СДЕЛАТЬ УДАЛЕНИЕ КНИГ
        self.enter_genre = QtWidgets.QLineEdit(AddBook)
        self.enter_genre.setGeometry(QtCore.QRect(150, 180, 113, 20))
        self.enter_genre.setObjectName("enter_genre")

        self.confirm_btn = QtWidgets.QPushButton(AddBook)
        self.confirm_btn.setGeometry(QtCore.QRect(90, 230, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Manrope")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_btn.setFont(font)
        self.confirm_btn.setStyleSheet("QPushButton {\n"
                                       "    border: 2px solid #8f8f91;\n"
                                       "    border-radius: 6px;\n"
                                       "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                       "                                      stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
                                       "    min-width: 80px;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed {\n"
                                       "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                       "                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:flat {\n"
                                       "    border: none; /* no border for a flat push button */\n"
                                       "}\n"
                                       "")
        self.confirm_btn.setObjectName("confirm_btn")
        self.label_title = QtWidgets.QLabel(AddBook)
        self.label_title.setGeometry(QtCore.QRect(20, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Manrope")
        font.setPointSize(11)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_writer = QtWidgets.QLabel(AddBook)
        self.label_writer.setGeometry(QtCore.QRect(20, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Manrope")
        font.setPointSize(11)
        self.label_writer.setFont(font)
        self.label_writer.setObjectName("label_writer")
        self.label_publisher = QtWidgets.QLabel(AddBook)
        self.label_publisher.setGeometry(QtCore.QRect(20, 100, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Manrope")
        font.setPointSize(11)
        self.label_publisher.setFont(font)
        self.label_publisher.setObjectName("label_publisher")
        self.label_lang = QtWidgets.QLabel(AddBook)
        self.label_lang.setGeometry(QtCore.QRect(20, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Manrope")
        font.setPointSize(11)
        self.label_lang.setFont(font)
        self.label_lang.setObjectName("label_lang")
        self.label_genre = QtWidgets.QLabel(AddBook)
        self.label_genre.setGeometry(QtCore.QRect(20, 180, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Manrope")
        font.setPointSize(11)
        self.label_genre.setFont(font)
        self.label_genre.setObjectName("label_genre")

        self.retranslateUi(AddBook)
        QtCore.QMetaObject.connectSlotsByName(AddBook)

    def retranslateUi(self, AddBook):
        _translate = QtCore.QCoreApplication.translate
        AddBook.setWindowTitle(_translate("AddBook", "Добавление книги"))
        self.confirm_btn.setText(_translate("AddBook", "Подтвердить"))
        self.label_title.setText(_translate("AddBook", "Название"))
        self.label_writer.setText(_translate("AddBook", "Автор"))
        self.label_publisher.setText(_translate("AddBook", "Издатель"))
        self.label_lang.setText(_translate("AddBook", "Язык"))
        self.label_genre.setText(_translate("AddBook", "Жанр"))
